# Generated by Django 3.2.3 on 2021-05-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_link', '0003_auto_20210516_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(db_index=True),
        ),
    ]
