# Generated by Django 3.2.3 on 2021-05-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_link', '0004_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
    ]
